{% set name = "prophecy-build-tool" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/prophecy-build-tool-{{ version }}.tar.gz
  sha256: 0f9e6de38489cf1a8fd56371fa3fa7ee762ef77b2cf53049f8d2ee1318b6d8a2

build:
  entry_points:
    - pbt = pbt:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests >=2.28.0
    - pyyaml >=6.0
    - databricks-cli >=0.17.7
    - rich >=12.5.1
    - wheel
    - python-build
    - pyspark ==3.3.0

test:
  imports:
    - pbt
  commands:
    - pip check
    - pbt --help
  requires:
    - pip

about:
  home: https://github.com/SimpleDataLabsInc/prophecy-build-tool
  summary: Prophecy-build-tool (PBT) provides utilities to build and distribute projects created from the Prophecy IDE.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
