{% set name = "prophecy-build-tool" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/prophecy-build-tool-{{ version }}.tar.gz
  sha256: b6e978d2dc495dae2803f0f82be1d262aba23d30fb4cfed77acfd3f9b83cc76f

build:
  entry_points:
    - pbt = pbt:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - click >=8.1.3
    - requests >=2.28.0
    - pyyaml >=6.0
    - databricks-cli >=0.17.7
    - rich >=12.5.1
    - wheel
    - python-build
    - pyspark ==3.3.0

test:
  imports:
    - pbt
  commands:
    - pip check
    - pbt --help
  requires:
    - pip

about:
  home: https://github.com/SimpleDataLabsInc/prophecy-build-tool
  summary: Prophecy-build-tool (PBT) provides utilities to build and distribute projects created from the Prophecy IDE.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
